/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunRunIdRouteImport } from './routes/run.$runId'
import { Route as ResultsRunIdRouteImport } from './routes/results.$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunRunIdRoute = RunRunIdRouteImport.update({
  id: '/run/$runId',
  path: '/run/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRunIdRoute = ResultsRunIdRouteImport.update({
  id: '/results/$runId',
  path: '/results/$runId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/results/$runId': typeof ResultsRunIdRoute
  '/run/$runId': typeof RunRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/results/$runId': typeof ResultsRunIdRoute
  '/run/$runId': typeof RunRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/results/$runId': typeof ResultsRunIdRoute
  '/run/$runId': typeof RunRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/results/$runId' | '/run/$runId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/results/$runId' | '/run/$runId'
  id: '__root__' | '/' | '/results/$runId' | '/run/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResultsRunIdRoute: typeof ResultsRunIdRoute
  RunRunIdRoute: typeof RunRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run/$runId': {
      id: '/run/$runId'
      path: '/run/$runId'
      fullPath: '/run/$runId'
      preLoaderRoute: typeof RunRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$runId': {
      id: '/results/$runId'
      path: '/results/$runId'
      fullPath: '/results/$runId'
      preLoaderRoute: typeof ResultsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResultsRunIdRoute: ResultsRunIdRoute,
  RunRunIdRoute: RunRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
